force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>The Job listing/posting we are interesting in applying for</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who is applying for this role?</description>
    <label>Applicant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>The job posting this application is related to</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <formula>Job__r.Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Interview__c/Job_Interview__c.object-meta.xml
<CustomObject>
    <label>Job Interview</label>
    <nameField>
        <label>Job Interview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <description>Date of the interview.</description>
    <label>Interview Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Interview__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Job Interviews</relationshipLabel>
    <relationshipName>Job_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/interviewEmail.cls
public class InterviewEmail implements Schedulable {
    public void execute(SchedulableContext sc) {
        List<String> toaddress = new List <String> ();        

        Date tomorrow = Date.today().addDays(1);

        List<Job_Interview__c> upcomingInterviews = [SELECT Id, Interview_Date__c, Name,
                                                    Interview_Time__c,
                                                    Job_Application__r.Job__r.Company_Name__c,
                                                    Job_Application__r.Job__r.Title__c,
                                                    Job_Application__r.Applicant__r.Name,
                                                    Job_Application__r.Applicant__r.Email
                                                    FROM Job_Interview__c WHERE Interview_Date__c =:tomorrow];

        System.debug('Upcoming interviews'  + upcomingInterviews);
        String userTimeZone = UserInfo.getTimeZone().getID();
        DateTime myDateTime = DateTime.newInstance(Date.today(), upcomingInterviews[0].Interview_Time__c);
        // Format the DateTime object to get the time in the user's local time zone
        String formattedTime = myDateTime.format('h:mm a', userTimeZone);
        System.debug('Formatted Time (Local): ' + formattedTime);

        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();
        for (Job_Interview__c interview : upcomingInterviews) {
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            if ((interview.Job_Application__r.Applicant__r.Email == NULL) ||
                String.isBlank(interview.Job_Application__r.Applicant__r.Email)) {
                    continue;
            }

            List <String> toAddr = new List<String> ();
            mail.setSubject('Upcoming Interview Reminder');
            mail.setPlainTextBody('Dear ' + interview.Job_Application__r.Applicant__r.Name+ ',\n\n' +
                                  'This is to remind you of the upcoming interview scheduled for tomorrow with ' + 
                                   interview.Job_Application__r.Job__r.Company_Name__c + ' at ' + 
                                   + formattedTime +
                                   ' for the ' + 
                                   interview.Job_Application__r.Job__r.Title__c + ' position.' +
                                   '\n\nThank you.');
            
            mail.setSaveAsActivity(false);
            toAddr.add(interview.Job_Application__r.Applicant__r.Email);
            mail.setToAddresses(toAddr);
            emailMessages.add(mail);
            System.debug('+++ ' + interview.Job_Application__r.Applicant__r.Email);
        }
        List<Messaging.SendEmailResult>  sendEmailResults = Messaging.sendEmail(emailMessages);
        System.debug(emailMessages);
    }
}