force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>The Job listing/posting we are interesting in applying for</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of job listed</description>
    <label>Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who is applying for this role?</description>
    <label>Applicant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>The job posting this application is related to</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <formula>Job__r.Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Interview__c/Job_Interview__c.object-meta.xml
<CustomObject>
    <label>Job Interview</label>
    <nameField>
        <label>Job Interview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <description>Date of the interview.</description>
    <label>Interview Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Interview__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Job Interviews</relationshipLabel>
    <relationshipName>Job_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testInterviewEmail.cls
/*
 * Test that :
 *  - An interview with a NULL/Invalid time doesn't get scheduled. The expected behaciour is that
 *   the trigger for insert will throw an exception
 *  - A test interview with a valid time gets scheduled. 
 *   This is done by checking if there is a cron expression with the same time as ours scheduled Email Job
 *   in the list of Cron Triggers
*/

@isTest
public with sharing class testInterviewEmail {
    @isTest
    static void interviewEmailTestvalidDate() {
        List <User> users = new List <User> ();
        users = [SELECT ID, Email, Name FROM User];
		
        Job__c job = new Job__c(Title__c = 'Salesforce Developer',
                                Company_Name__c = 'Cloudcode');
        insert job;
        Job_Application__c jobApp = new Job_Application__c(Job__c = job.id, Name='testClassJob1',
                                                           Applicant__c = users[0].id);
        insert jobApp;
        Time intTime = DateTime.now().time().addMinutes(1);
        Date intDate = Date.today().addDays(1);
        Job_Interview__c jobInt = new Job_Interview__c(Interview_Time__c = intTime,
                                                       Interview_Date__c = intDate,
                                                       Job_Application__c = jobApp.id);
		
        Job_Interview__c jobInt2 = new Job_Interview__c(Interview_Time__c = NULL,
                                                       Interview_Date__c = intDate,
                                                       Job_Application__c = jobApp.id);
		//Check that a NULL time throws exception
        Test.startTest();
		//Assert
        try {
    		insert jobInt2;
		} catch (DmlException e)  {
            Assert.isTrue(e.getMessage().contains('Date or time cant be null or invalid'), 'Unexpected exception on insert');
		}
        insert jobInt;
        Test.stopTest();

        String minute = intTime.minute().toString(); //can't be typcast
        String hour = intTime.hour().toString();
        String day = (intDate.day() - 1).toString();
        String schDayBefore = '0' + ' ' + minute + ' ' + hour + ' '  + day + ' '  + intDate.month() + ' '  + '?' + ' ' + intDate.year();

        List<CronTrigger> ct = [SELECT Id, CronExpression, TimesTriggered, 
        NextFireTime
        FROM CronTrigger];

       // check that the apex job for sending email was scheduled
       Integer foundCron;
	   for (CronTrigger ctSch : ct) {
           if (schDayBefore.equals(ctSch.CronExpression)) {
               foundCron = 1;
           }
	   }
       Assert.areEqual(1, foundCron, 'cron job for email not scheduled');
    }
}