force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>The Job listing/posting we are interesting in applying for</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of job listed</description>
    <label>Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who is applying for this role?</description>
    <label>Applicant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>The job posting this application is related to</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <formula>Job__r.Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Interview__c/Job_Interview__c.object-meta.xml
<CustomObject>
    <label>Job Interview</label>
    <nameField>
        <label>Job Interview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <description>Date of the interview.</description>
    <label>Interview Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Interview__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Job Interviews</relationshipLabel>
    <relationshipName>Job_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InterviewEmail_Test.cls
/*
 *Test that :
 * - An interview with a NULL/Invalid time doesn't get scheduled. The expected behaciour is that
 *   the trigger for insert Job_interview_c will throw an exception
 * 
 * - A bunch of interviews with a valid time gets scheduled. 
 *   This is done by checking that our CronJob is submitted. We also check that expected number of
 *   emails have been sent
*/

@isTest
public with sharing class InterviewEmail_Test {
    @isTest
    static void interviewEmailTestInvalidDate() {
        List <User> users = new List <User> ();

        users = [SELECT ID, Email, Name FROM User];
		
        Job__c job = new Job__c(Title__c = 'Salesforce Developer',
                                Company_Name__c = 'Cloudcode');
        insert job;

        //create a job and application for a user
        Job_Application__c jobApp = new Job_Application__c(Job__c = job.id, Name='testClassJob1',
                                                           Applicant__c = users[0].id);
        insert jobApp;
        Time intTime = DateTime.now().time().addMinutes(1);
        Date intDate = Date.today().addDays(1);

        //create a job interviewe and for above application
        Job_Interview__c jobInt = new Job_Interview__c(Interview_Time__c = NULL,
                                                       Interview_Date__c = intDate,
                                                       Job_Application__c = jobApp.id);
		//Check that a NULL time throws exception
        Test.startTest();
		//Assert
        try {
    		insert jobInt;
		} catch (DmlException e)  {
            Assert.isTrue(e.getMessage().contains('Date or time cant be null or invalid'), 'Unexpected exception on insert');
		}
        Test.stopTest();
    }

    /**
     * create 4 jobs with valid date time and check that they get scheduled
     * and reminder emails are indeed sent
     */
    @isTest
    static void interviewEmailTestvalidDate() {
        List <User> users = new List <User> ();
        Integer i;
        
        users = [SELECT ID, Email, Name FROM User];
		
        Job__c job = new Job__c(Title__c = 'Salesforce Developer',
                                Company_Name__c = 'Cloudcode');
        insert job;
        Job_Application__c jobApp = new Job_Application__c(Job__c = job.id, Name='testClassJob1',
                                                           Applicant__c = users[0].id);
        insert jobApp;
        Time intTime = DateTime.now().time();
        Date intDate = Date.today().addDays(1);
        List <Job_Interview__c> jobInts = new List<Job_Interview__c>();

        for (i=0 ; i < 4; i++) {
            jobInts.add(new Job_Interview__c(Interview_Time__c = intTime.addMinutes(i),
                                                       Interview_Date__c = intDate,
                                                       Job_Application__c = jobApp.id));
        }

        Test.startTest();
        insert jobInts;
        Test.stopTest();

        //check that our job got scheduled
        List<CronTrigger> scheduledJobs = [SELECT Id, CronJobDetail.Name, CronJobDetail.JobType, State, NextFireTime, StartTime
                                            FROM CronTrigger WHERE CronJobDetail.Name = :'InterviewReminder'];

        System.assertEquals(scheduledJobs[0].CronJobDetail.Name, 'InterviewReminder',
                        'Email reminder Job was not scheduled');

        //check that emails got sent for all 4 interviews with the right subject
        List<EmailMessage> emailMessages = [SELECT Id, Subject, TextBody FROM EmailMessage];
        System.assertEquals(emailMessages.size(), 4, 'Expected 4 emails' + 'Sent ' + emailMessages.size());
    }
}