force-app/main/default/objects/Job_Interview__c/Job_Interview__c.object-meta.xml
<CustomObject>
    <label>Job Interview</label>
    <nameField>
        <label>Job Interview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <description>Date of the interview.</description>
    <label>Interview Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/InterviewEmailHelper.cls
public with sharing class InterviewEmailHelper {
    public static void schdInterviewReminder (List <Job_Interview__c> jobList) {
        String schDayBefore;
        for (Job_Interview__c newInterview : jobList) {
            Date intDate = newInterview.Interview_Date__c;
            Time intTime = newInterview.Interview_Time__c;

            if (intdate != Null && intTime != Null) {
                String minute = intTime.minute().toString();
                String hour = intTime.hour().toString();
                String day = (intDate.day() - 1).toString();

                //Make the cron expression for the day before from the interview time and date
                schDayBefore = '0' + ' ' + minute + ' ' + hour + ' '  + day + ' '  + intDate.month() + ' '  + '?' + ' ' + intDate.year();
                String schString = 'Scheduled Interview' + math.random();
                interviewEmail jobReminder = new interviewEmail(newInterview.Id);
                // Pass in the Interviw Id so that the SOQL query is effecient
                String jobID = System.schedule(schString, schDayBefore, jobReminder);
            } else {
                newInterview.addError('Date or time cant be null or invalid');
            }
        }
    }
}