force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>This field allows users to specify the role of each contact involved in recruitment and hiring activities</description>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recruiter</fullName>
            </value>
            <value>
                <fullName>Hiring Manager</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>The Job listing/posting we are interesting in applying for</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company that has the job opening</description>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who is applying for this role?</description>
    <label>Applicant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_date__c</fullName>
    <description>Specifies when to follow up on the application.</description>
    <label>Follow-up date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>The job posting this application is related to</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Tracks the current status of the job application.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloseStaleApplications_Test.cls
@isTest
public with sharing class CloseStaleApplications_Test {
    @IsTest
    public static void testCloseStaleApplications_Schedule() {
         // Create test data
        Account testAccount1 = new Account(Name = 'Test Account');
        insert testAccount1;

        List<Contact> testContacts = new List<Contact>();
        Contact testContact1 = new Contact(LastName = 'Test', AccountId = testAccount1.Id, Role__c = 'Recruiter');
        insert testContact1;

        Job__c testJob = new Job__c(Name = 'Test Job', Company__c = testAccount1.Id);
        insert testJob;

        Job_Application__c testJobApplication = new Job_Application__c(
            Name = 'Test Job Application',
            Company_Name__c = testAccount1.id,
            Job__c = testJob.Id,
            Applicant__c = [SELECT Id FROM User WHERE IsActive = true LIMIT 1].Id,
            Primary_Contact__c = testContact1.Id,
            Status__c = 'Saved',
            Follow_up_date__c = Date.today().addDays(-45)
        );   
        System.debug('testJobApplication: ' + testJobApplication);
        insert testJobApplication;

        // Schedule the CloseStaleApplications_Schedulable class for execution
        Test.startTest();
        CloseStaleApplications_Schedulable closeStaleApplications = new CloseStaleApplications_Schedulable();
        String year = String.valueOf(Date.today().year() + 1);
        String cron = '0 0 0 15 3 ? ' + year; // Arbitrary cron expression for once-off execution in the future
        //Seconds Minutes Hours Day_of_month Month Day_of_week Optional_year
        //'?' Specifies no specific value. This option is only available for Day_of_month and Day_of_week. It’s typically used when specifying a value for one and not the other.
        System.debug('cron: ' + cron);
        System.schedule('CloseStaleApplsTest', cron, closeStaleApplications);
        closeStaleApplications.execute(null);
        Test.stopTest();

        // Query the updated job applications
        List<Job_Application__c> updatedJobApplications = [SELECT Id, Status__c 
                                                            FROM Job_Application__c 
                                                            WHERE Id = :testJobApplication.Id];
        System.debug('updatedJobApplications: ' + updatedJobApplications);
    

        // Assert that all job applications's Status__c fields are updated
        for (Job_Application__c jobApp : updatedJobApplications) {
            System.assertEquals('Closed', jobApp.Status__c, 'Job Application Status__c field was not updated correctly.');
        }
    }
}