force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>This field allows users to specify the role of each contact involved in recruitment and hiring activities</description>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recruiter</fullName>
            </value>
            <value>
                <fullName>Hiring Manager</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>The Job listing/posting we are interesting in applying for</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company that has the job opening</description>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who is applying for this role?</description>
    <label>Applicant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>The job posting this application is related to</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Tracks the current status of the job application.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerHandler_Test.cls
@isTest
public with sharing class JobApplicationTriggerHandler_Test {

    @isTest
    static void testCreateTaskFromStatus() {
        // Test data setup
        
        Account testAccount1 = new Account(Name = 'Test Account');
        insert testAccount1;

        List<Contact> testContacts = new List<Contact>();
        Contact testContact1 = new Contact(LastName = 'Test', AccountId = testAccount1.Id, Role__c = 'Recruiter');
        insert testContact1;

        Job__c testJob = new Job__c(Name = 'Test Job', Company__c = testAccount1.Id);
        insert testJob;

        Job_Application__c testJobApplication = new Job_Application__c(
            Name = 'Test Job Application',
            Company_Name__c = testAccount1.id,
            Job__c = testJob.Id,
            Applicant__c = [SELECT Id FROM User WHERE IsActive = true LIMIT 1].Id,
            Primary_Contact__c = testContact1.Id,
            Status__c = 'Saved'
        );
        
        insert testJobApplication;
        System.debug('The test application: ' + testJobApplication);

        // Test execution
        Test.startTest();
        JobApplicationTriggerHandler.createTaskFromStatus(new List<Job_Application__c>{testJobApplication});
        Test.stopTest();

        // Test verification
        List<Task> tasks = [SELECT Id FROM Task WHERE Job_Application__c = :testJobApplication.Id];
        System.debug('The generated Task: ' + tasks);
        Assert.areEqual(2, tasks.size(), 'Expected 1 task to be created');
    }
}